### ISSUE TITLE
Error handling: Status text missing for the "insufficient funds" case

### ISSUE THREAD

**Issue by hacklschorsch** [PrivateStorageio/PaymentServer#112]
Trying to buy storage-time with a card with insufficient funds currently results in a "400" HTTP error without any further information.

Having a `statusText` to display ([frontend code here](https://whetstone.private.storage/privatestorage/privatestorageweb/-/merge_requests/91/diffs#b3c4f1c8ecd2f24606b1dab692e058e50447a08e_48_48)) would be helpful.

Screenshot by Eric:
![payment processing error](https://user-images.githubusercontent.com/454605/156204243-b2d2031e-e538-4b32-98d8-6dea22204ec3.png)
 
I look at [Monitoring for around that time](https://monitoring.privatestorage.io/d/Payments/payments?orgId=1&from=1646130848091&to=1646131245552) and it seems it was indeed "insufficient funds":
```
2022-03-01 10:07:51  POST /v1/stripe/charge
2022-03-01 10:07:51  "Stripe createCharge failed:"
2022-03-01 10:07:51  "Your card has insufficient funds."
```
The related error on the server also has no statusText:
```
2022-03-01 10:07:51	
  Status: 400  1.732255581s
```

Maybe related to #50.
Maybe already fixed by #111.

**Comment by exarkun** [comment]
I think this is "client" error.  PaymentServer doesn't return the Stripe message in the HTTP status text.  It returns it in the JSON-encoded response body on the `reason` property.

I think I reviewed that JavaScript code, so my bad. :/

**Comment by hacklschorsch** [comment]
I still think PaymentServer should put *some* status text in there.

From [here](https://monitoring.privatestorage.io/explore?orgId=1&left=%5B%221646128800000%22,%221646131500000%22,%22Loki%22,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bhost%3D%5C%22payments%5C%22,job%3D%5C%22systemd-journal%5C%22%7D%20%7C%3D%20%5C%22400%5C%22%22%7D%5D):

<img width="427" alt="image" src="https://user-images.githubusercontent.com/454605/156340918-54e9068d-2cfa-4d76-9c4a-b495f5a0c3c2.png">

**Comment by hacklschorsch** [comment]
Excerpt of [RFC 7230: Hypertext Transfer Protocol (HTTP/1.1): Message Syntax and Routing, Section 3.1.2: Status Line](https://www.rfc-editor.org/rfc/rfc7230.html#section-3.1.2)

> The first line of a response message is the status-line, consisting
   of the protocol version, a space (SP), the status code, another
   space, a **possibly empty** textual phrase describing the status code,
   and ending with CRLF.

(Emphasis mine.)

So yes, the status text may be empty. I still think it's bad style ;)

**Comment by exarkun** [comment]
Okay.  We can put "Bad Request" here at some point, but I don't think it will help anyone. :)
